### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by abteenz** [pierre-24/timeflip-tt#3]
C:\Users\abtee>timeflip-tt
 * Serving Flask app 'timefliptt.app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
[2022-05-14 23:24:42,765] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\views.py", line 158, in dispatch_request
    return current_app.ensure_sync(meth)(*args, **kwargs)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\timefliptt\blueprints\base_views.py", line 32, in get
    return flask.render_template(self.template_name, **context_data)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: visitors/graphs.html
127.0.0.1 - - [14/May/2022 23:24:42] "GET / HTTP/1.1" 500 -
127.0.0.1 - - [14/May/2022 23:24:43] "GET /favicon.ico HTTP/1.1" 404 -
[2022-05-14 23:25:17,526] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\views.py", line 158, in dispatch_request
    return current_app.ensure_sync(meth)(*args, **kwargs)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\timefliptt\blueprints\base_views.py", line 32, in get
    return flask.render_template(self.template_name, **context_data)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: visitors/graphs.html
127.0.0.1 - - [14/May/2022 23:25:17] "GET / HTTP/1.1" 500 -
[2022-05-14 23:25:19,782] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\views.py", line 158, in dispatch_request
    return current_app.ensure_sync(meth)(*args, **kwargs)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\timefliptt\blueprints\base_views.py", line 32, in get
    return flask.render_template(self.template_name, **context_data)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: visitors/graphs.html
127.0.0.1 - - [14/May/2022 23:25:19] "GET / HTTP/1.1" 500 -
[2022-05-14 23:25:26,570] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\views.py", line 158, in dispatch_request
    return current_app.ensure_sync(meth)(*args, **kwargs)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\timefliptt\blueprints\base_views.py", line 32, in get
    return flask.render_template(self.template_name, **context_data)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: visitors/graphs.html
127.0.0.1 - - [14/May/2022 23:25:26] "GET / HTTP/1.1" 500 -
[2022-05-14 23:25:28,344] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\views.py", line 158, in dispatch_request
    return current_app.ensure_sync(meth)(*args, **kwargs)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\timefliptt\blueprints\base_views.py", line 32, in get
    return flask.render_template(self.template_name, **context_data)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: visitors/graphs.html
127.0.0.1 - - [14/May/2022 23:25:28] "GET / HTTP/1.1" 500 -
[2022-05-14 23:30:09,832] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\views.py", line 158, in dispatch_request
    return current_app.ensure_sync(meth)(*args, **kwargs)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\timefliptt\blueprints\base_views.py", line 32, in get
    return flask.render_template(self.template_name, **context_data)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\abtee\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: visitors/graphs.html
127.0.0.1 - - [14/May/2022 23:30:09] "GET / HTTP/1.1" 500 -

**Comment by pierre-24** [comment]
Hello,

Thanks for reporting this. It is most probably due to the fact that I totally forgot one step in [the flask tutorial](https://flask.palletsprojects.com/en/2.1.x/tutorial/install/) to package the application (the `MANIFEST.in` is missing).

**Comment by abteenz** [comment]
I'm a total noob in programming. The native application coming with Timeflip is so bad that it encouraged me to pickup programming again and write an application to my likings. Any Idea if the device has an internal clock or not? Thanks!

**Comment by pierre-24** [comment]
It does have an internal clock, but stores the data in the form `duration, facet`. See, for example, [there](https://github.com/pierre-24/pytimefliplib/blob/master/protocol_v3_corrected.md) for the API, which is pretty straightforward if you are use to BLE devices :)

**Comment by abteenz** [comment]
You are a genius. I was able to send commands to the devices providing the
password everytime before executing a command.

So basically the device is not capable of giving you the start time and the
end time for the activity? I specifically want to have logs that says you
started coding at 3:00 PM and and ended at 4:00 instead of you just coded
for 1 hour today.
